declare namespace net.runelite.api {
	export interface IconID {
		PLAYER_MODERATOR: 'PLAYER_MODERATOR';
		JAGEX_MODERATOR: 'JAGEX_MODERATOR';
		IRONMAN: 'IRONMAN';
		ULTIMATE_IRONMAN: 'ULTIMATE_IRONMAN';
		DMM_SKULL_5_KEYS: 'DMM_SKULL_5_KEYS';
		DMM_SKULL_4_KEYS: 'DMM_SKULL_4_KEYS';
		DMM_SKULL_3_KEYS: 'DMM_SKULL_3_KEYS';
		DMM_SKULL_2_KEYS: 'DMM_SKULL_2_KEYS';
		DMM_SKULL_1_KEYS: 'DMM_SKULL_1_KEYS';
		SKULL: 'SKULL';
		HARDCORE_IRONMAN: 'HARDCORE_IRONMAN';
		NO_ENTRY: 'NO_ENTRY';
		CHAIN_LINK: 'CHAIN_LINK';
		BOUNTY_HUNTER_EMBLEM: 'BOUNTY_HUNTER_EMBLEM';
		LEAGUE: 'LEAGUE';
	}
}
