declare namespace net.runelite.api {
	export enum InstanceTemplates {
		RAIDS_LOBBY = 'RAIDS_LOBBY',
		RAIDS_START = 'RAIDS_START',
		RAIDS_END = 'RAIDS_END',
		RAIDS_SCAVENGERS = 'RAIDS_SCAVENGERS',
		RAIDS_SHAMANS = 'RAIDS_SHAMANS',
		RAIDS_VASA = 'RAIDS_VASA',
		RAIDS_VANGUARDS = 'RAIDS_VANGUARDS',
		RAIDS_ICE_DEMON = 'RAIDS_ICE_DEMON',
		RAIDS_THIEVING = 'RAIDS_THIEVING',
		RAIDS_FARMING = 'RAIDS_FARMING',
		RAIDS_SCAVENGERS2 = 'RAIDS_SCAVENGERS2',
		RAIDS_MUTTADILES = 'RAIDS_MUTTADILES',
		RAIDS_MYSTICS = 'RAIDS_MYSTICS',
		RAIDS_TEKTON = 'RAIDS_TEKTON',
		RAIDS_TIGHTROPE = 'RAIDS_TIGHTROPE',
		RAIDS_FARMING2 = 'RAIDS_FARMING2',
		RAIDS_GUARDIANS = 'RAIDS_GUARDIANS',
		RAIDS_VESPULA = 'RAIDS_VESPULA',
		RAIDS_CRABS = 'RAIDS_CRABS',
	}
}
