declare namespace net.runelite.api {
	export interface Skill {
		ATTACK: 'ATTACK';
		DEFENCE: 'DEFENCE';
		STRENGTH: 'STRENGTH';
		HITPOINTS: 'HITPOINTS';
		RANGED: 'RANGED';
		PRAYER: 'PRAYER';
		MAGIC: 'MAGIC';
		COOKING: 'COOKING';
		WOODCUTTING: 'WOODCUTTING';
		FLETCHING: 'FLETCHING';
		FISHING: 'FISHING';
		FIREMAKING: 'FIREMAKING';
		CRAFTING: 'CRAFTING';
		SMITHING: 'SMITHING';
		MINING: 'MINING';
		HERBLORE: 'HERBLORE';
		AGILITY: 'AGILITY';
		THIEVING: 'THIEVING';
		SLAYER: 'SLAYER';
		FARMING: 'FARMING';
		RUNECRAFT: 'RUNECRAFT';
		HUNTER: 'HUNTER';
		CONSTRUCTION: 'CONSTRUCTION';
	}
}
