/// <reference path="../../../java/index.d.ts" />
/// <reference path="../Point.d.ts" />
/// <reference path="../FontTypeFace.d.ts" />
interface Widget {
	getId(): number;
	getType(): number;
	setType(type: number): void;
	getContentType(): number;
	setContentType(contentType: number): Widget;
	getClickMask(): number;
	setClickMask(mask: number): Widget;
	getParent(): Widget | null;
	getParentId(): number;
	getChild(index: number): Widget | null;
	getChildren(): Widget[] | null;
	setChildren(children: Widget[]): void;
	getDynamicChildren(): Widget[];
	getStaticChildren(): Widget[];
	getNestedChildren(): Widget[];
	getRelativeX(): number;
	setRelativeX(x: number): void;
	getRelativeY(): number;
	setRelativeY(y: number): void;
	setForcedPosition(x: number, y: number): void;
	getText(): string;
	setText(text: string): Widget;
	getTextColor(): number;
	setTextColor(textColor: number): Widget;
	getOpacity(): number;
	setOpacity(transparency: number): Widget;
	getName(): string;
	setName(name: string): Widget;
	getModelId(): number;
	setModelId(id: number): Widget;
	getModelType(): number;
	setModelType(type: number): Widget;
	getAnimationId(): number;
	setAnimationId(animationId: number): Widget;
	getRotationX(): number;
	setRotationX(modelX: number): Widget;
	getRotationY(): number;
	setRotationY(modelY: number): Widget;
	getRotationZ(): number;
	setRotationZ(modelZ: number): Widget;
	getModelZoom(): number;
	setModelZoom(modelZoom: number): Widget;
	getSpriteId(): number;
	getSpriteTiling(): boolean;
	setSpriteTiling(tiling: boolean): Widget;
	setSpriteId(spriteId: number): Widget;
	isHidden(): boolean;
	isSelfHidden(): boolean;
	setHidden(hidden: boolean): Widget;
	getIndex(): number;
	getCanvasLocation(): Point;
	getWidth(): number;
	setWidth(width: number): void;
	getHeight(): number;
	setHeight(height: number): void;
	getBounds(): Rectangle;
	getItemId(): number;
	setItemId(itemId: number): Widget;
	getItemQuantity(): number;
	setItemQuantity(quantity: number): Widget;
	contains(point: Point): boolean;
	getScrollX(): number;
	setScrollX(scrollX: number): Widget;
	getScrollY(): number;
	setScrollY(scrollY: number): Widget;
	getScrollWidth(): number;
	setScrollWidth(width: number): Widget;
	getScrollHeight(): number;
	setScrollHeight(height: number): Widget;
	getOriginalX(): number;
	setOriginalX(originalX: number): Widget;
	getOriginalY(): number;
	setOriginalY(originalY: number): Widget;
	setPos(x: number, y: number, xMode?: number, yMode?: number): Widget;
	getOriginalHeight(): number;
	setOriginalHeight(originalHeight: number): Widget;
	getOriginalWidth(): number;
	setOriginalWidth(originalWidth: number): Widget;
	setSize(
		width: number,
		height: number,
		widthMode?: number,
		heightMode?: number,
	): Widget;
	getActions(): string[] | null;
	createChild(index: number, type: number): Widget;
	createChild(type: number): Widget;
	deleteAllChildren(): void;
	setAction(index: number, action: string): void;
	setOnOpListener(...args: any[]): void;
	setOnDialogAbortListener(...args: any[]): void;
	setOnKeyListener(...args: any[]): void;
	setOnMouseOverListener(...args: any[]): void;
	setOnMouseRepeatListener(...args: any[]): void;
	setOnMouseLeaveListener(...args: any[]): void;
	setOnTimerListener(...args: any[]): void;
	setOnTargetEnterListener(...args: any[]): void;
	setOnTargetLeaveListener(...args: any[]): void;
	hasListener(): boolean;
	setHasListener(hasListener: boolean): Widget;
	isIf3(): boolean;
	revalidate(): void;
	revalidateScroll(): void;
	getOnOpListener(): any[];
	getOnKeyListener(): any[];
	getOnLoadListener(): any[];
	getOnInvTransmitListener(): any[];
	getFontId(): number;
	setFontId(id: number): Widget;
	getBorderType(): number;
	setBorderType(thickness: number): void;
	getTextShadowed(): boolean;
	setTextShadowed(shadowed: boolean): Widget;
	getDragDeadZone(): number;
	setDragDeadZone(deadZone: number): void;
	getDragDeadTime(): number;
	setDragDeadTime(deadTime: number): void;
	getItemQuantityMode(): number;
	setItemQuantityMode(itemQuantityMode: number): Widget;
	getXPositionMode(): number;
	setXPositionMode(xpm: number): Widget;
	getYPositionMode(): number;
	setYPositionMode(ypm: number): Widget;
	getLineHeight(): number;
	setLineHeight(lineHeight: number): Widget;
	getXTextAlignment(): number;
	setXTextAlignment(xta: number): Widget;
	getYTextAlignment(): number;
	setYTextAlignment(yta: number): Widget;
	getWidthMode(): number;
	setWidthMode(widthMode: number): Widget;
	getHeightMode(): number;
	setHeightMode(heightMode: number): Widget;
	getFont(): FontTypeFace;
	isFilled(): boolean;
	setFilled(filled: boolean): Widget;
	getTargetVerb(): string;
	setTargetVerb(targetVerb: string): void;
	getNoClickThrough(): boolean;
	setNoClickThrough(noClickThrough: boolean): void;
	getNoScrollThrough(): boolean;
	setNoScrollThrough(noScrollThrough: boolean): void;
	setVarTransmitTrigger(...trigger: number[]): void;
	setOnClickListener(...args: any[]): void;
	setOnHoldListener(...args: any[]): void;
	setOnReleaseListener(...args: any[]): void;
	setOnDragCompleteListener(...args: any[]): void;
	setOnDragListener(...args: any[]): void;
	setOnScrollWheelListener(...args: any[]): void;
	getDragParent(): Widget;
	setDragParent(dragParent: Widget): Widget;
	getOnVarTransmitListener(): any[];
	setOnVarTransmitListener(...args: any[]): void;
}
